---
- name: Get apt updates.
  apt:
    update_cache: yes
    cache_valid_time: "{{ aptget_update_cache_valid_time }}"
  when: aptget_update

- name: Simple apt upgrade.
  apt:
    upgrade: safe
    update_cache: yes
  when: aptget_upgrade

- name: Apt distro upgrade.
  apt:
    upgrade: full
    update_cache: yes
  when: aptget_distupgrade
